version: '3.8'

networks:
  ansible_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24  # サブネットを指定

services:
  ansible:
    image: williamyeh/ansible:alpine3
    container_name: ansible
    networks:
      ansible_network:
        ipv4_address: 192.168.1.32
    volumes:
      - ./ansible_project:/ansible_project
    entrypoint: /bin/sh -c "while true; do sleep 1000; done"
    environment:
      - ANSIBLE_HOST_KEY_CHECKING=False

  web1:
    image: yourdockerhubusername/web1-ssh-ready
    container_name: web1
    networks:
      ansible_network:
        ipv4_address: 192.168.1.33
    tty: true
    stdin_open: true
    command: ["/bin/sh", "-c", "ssh-keygen -A && /usr/sbin/sshd -D"]

  web2:
    image: yourdockerhubusername/web2-ssh-ready
    container_name: web2
    networks:
      ansible_network:
        ipv4_address: 192.168.1.34
    tty: true
    stdin_open: true
    command: ["/bin/sh", "-c", "ssh-keygen -A && /usr/sbin/sshd -D"]